version: "3.7"

services:
  redis:
    image: redis:latest
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "scale.js"]
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis